image: node:18.12.0-bullseye

stages:
- setup
- build
- test

install:
  stage: setup
  script:
    - npm ci

build:
  stage: build
  script:
    - npm ci
    - npm run build

unit_test:
  stage: test
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
    - npm update
  script:
    - npm ci
    - npm run test --no-watch --browsers=ChromeHeadlessCI