image: node:18.12.0-bullseye

stages:
- setup
- test

install:
  stage: setup
  script:
    - npm ci

unit_test:
  stage: test
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm ci
    - npm run test -- --no-watch --browser=ChromeHeadlessCI